version: '2.3'
services:
  iridescent:
    image: registry.gitlab.com/pouyanh/iridescent:latest
    command:
      - "server"
      - "-D"
      - "--bind=0.0.0.0"
      - "--port=80"
      - "--appendPort=false"
      - "--baseURL=http://iridescent.pouyanh.jst/"
    environment:
      HOSTNAME: iridescent.pouyanh.jst
